# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0002_auto_20170824_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bad_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punish_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(choices=[('s', 'shelian'), ('l', 'zhidaolaoshi'), ('z', 'zheliba')], max_length=1)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Association')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('a', 'All'), ('b', 'Big'), ('x1', 'Xiao1'), ('x2', 'Xiao2')], max_length=2)),
                ('status', models.CharField(choices=[('11', 'LDealing'), ('12', 'SDealing'), ('13', 'ZDealing'), ('2', 'OK'), ('31', 'LCancled'), ('32', 'LCancled'), ('33', 'LCancled'), ('4', 'Done')], max_length=2)),
                ('Lanswer', models.CharField(max_length=100, null=True)),
                ('Sanswer', models.CharField(max_length=100, null=True)),
                ('Zanswer', models.CharField(max_length=100, null=True)),
                ('rtype', models.CharField(choices=[('n', 'normal'), ('s', 'shetuan')], max_length=1)),
                ('up_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Association')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Guest')),
            ],
        ),
        migrations.AddField(
            model_name='bad_record',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Record'),
        ),
    ]
