# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20170824_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('11', 'LDealing'), ('12', 'SDealing'), ('13', 'ZDealing'), ('2', 'OK'), ('31', 'LCancled'), ('32', 'SCancled'), ('33', 'ZCancled'), ('4', 'Done')], max_length=2),
        ),
    ]
