# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20170824_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='day_time',
            field=models.DateField(null=True),
        ),
    ]
