# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20170906_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Association'),
        ),
    ]
